---
name: 'Format check ArkScript code'
description: 'Given a folder, find all .ark files and check that they are correctly formatted'
inputs:
  folder:
    description: 'Folder with .ark files to check'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Download ArkScript latest release
      shell: sh
      run: |
        VERSION=linux-gcc-14
        wget -q $(curl -s https://api.github.com/repos/ArkScript-lang/Ark/releases?per_page=1 | grep "browser_download_url.*${VERSION}.zip" | cut -d : -f 2,3 | tr -d \")
        unzip -o ${VERSION}.zip
        chmod u+x ./arkscript
        ./arkscript --version

    - name: Check
      shell: bash
      run: |
        failures=0
        while read -rd $'\0' file; do
          if ! ./arkscript --format "$file" --check; then
            echo "❌ $(basename $file) is not formatted correctly"
            failures=$((failures+1))
          else
            echo "✅ $(basename $file)"
          fi
        path=${{ inputs.folder }}
        done < <(find "${path%/}" -type f -name "*.ark" -maxdepth 1 -print0)

        echo "$failures file(s) need to be formatted"
        [ $failures -gt 0 ] && exit 1 || exit 0
