---
name: 'Format check ArkScript code'
description: 'Given a folder, find all .ark files and check that they are correctly formatted'
inputs:
  folder:
    description: 'Folder with .ark files to check'
    required: true
  exclude:
    description: 'Folders to exclude, comma separated'

runs:
  using: 'composite'

  steps:
    - name: Download ArkScript latest release
      shell: sh
      run: |
        VERSION=linux-gcc-14
        wget -q $(curl -s https://api.github.com/repos/ArkScript-lang/Ark/releases?per_page=1 | grep "browser_download_url.*${VERSION}.zip" | cut -d : -f 2,3 | tr -d \")
        unzip -o ${VERSION}.zip
        chmod u+x ./arkscript
        ./arkscript --version

    - name: Check
      shell: bash
      run: |
        exclusions=''
        if ! [ -z "${{ inputs.exclude }}" ]; then
          IFS=',' read -ra EXC <<< "${{ inputs.exclude }}"
          for i in "${EXC[@]}"; do
            # process "$i"
            exclusions="$exclusions -not -path '$i/*'"
          done
          echo "Exclusions: '$exclusions'"
        fi

        failures=0
        while read -rd $'\0' file; do
          if ! ./arkscript --format "$file" --check; then
            echo "❌ $(basename $file) is not formatted correctly"
            failures=$((failures+1))
          else
            echo "✅ $(basename $file)"
          fi
        done < <(find "${{ inputs.folder }}" -type f -name "*.ark" $exclusions -print0)
        echo "$failures file(s) need to be formatted"
        [ $failures -gt 0 ] && exit 1 || exit 0
